[book]
authors = ["Georgios Konstantopoulos"]
language = "en"
multilingual = false
src = "src"
title = "The Senior Solidity Engineer's Book"

[output.html]
additional-js = [
    "theme/solidity.js",
    "theme/mermaid.min.js",
    "theme/mermaid-init.js",
]
mathjax-support = true

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

